wandb_version: 1

Learner:
  desc: null
  value:
    _name: <fastai.learner.Learner object at 0x00000225451938E0>
    act_cls: fastai.layers.Mish
    arch: torchvision.models.resnet.resnet34
    loss_func:
      _name: FlattenedLoss of CrossEntropyLoss()
      axis: 1
      flatten: true
      floatify: false
      is_2d: true
    lr: 0.001
    metrics: __main__.acc_camvid
    model_dir: models
    moms:
    - 0.95
    - 0.85
    - 0.95
    n_out: 2
    normalize: true
    opt_func: fastai.optimizer.ranger
    path: .
    pretrained: true
    self_attention: true
    splitter: fastai.vision.learner._resnet_split
    train_bn: true
    wd: null
    wd_bn_bias: false
ParamScheduler:
  desc: null
  value: true
ProgressCallback:
  desc: null
  value: true
Recorder:
  desc: null
  value:
    add_time: true
    train_metrics: false
    valid_metrics: true
TrainEvalCallback:
  desc: null
  value: true
WandbCallback:
  desc: null
  value:
    dataset_name: null
    log: gradients
    log_dataset: false
    log_model: true
    log_preds: true
    n_preds: 36
    reorder: true
    seed: 12345
    valid_dl: null
_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 4
      - 5
      4: 3.8.5
      5: 0.10.22
      8:
      - 1
      - 3
      - 5
batch per epoch:
  desc: null
  value: 61
batch size:
  desc: null
  value: 8
dataset.tfms:
  desc: null
  value: '[Pipeline: PILBase.create, Pipeline: <lambda> -> PILBase.create]'
device:
  desc: null
  value: cpu
dls.after_batch:
  desc: null
  value: "Pipeline: IntToFloatTensor -- {'div': 255.0, 'div_mask': 1} -> Flip -- {'size':\
    \ (200, 200), 'mode': 'bilinear', 'pad_mode': 'reflection', 'mode_mask': 'nearest',\
    \ 'align_corners': True, 'p': 0.5} -> Brightness -- {'max_lighting': 0.2, 'p':\
    \ 1.0, 'draw': None, 'batch': False} -> Normalize -- {'mean': tensor([[[[0.4850]],\n\
    \n         [[0.4560]],\n\n         [[0.4060]]]]), 'std': tensor([[[[0.2290]],\n\
    \n         [[0.2240]],\n\n         [[0.2250]]]]), 'axes': (0, 2, 3)}"
dls.after_item:
  desc: null
  value: 'Pipeline: AddMaskCodes -> ToTensor'
dls.before_batch:
  desc: null
  value: 'Pipeline: '
frozen:
  desc: null
  value: true
frozen idx:
  desc: null
  value: 2
input 1 dim 1:
  desc: null
  value: 8
input 1 dim 2:
  desc: null
  value: 3
input 1 dim 3:
  desc: null
  value: 200
input 1 dim 4:
  desc: null
  value: 200
model parameters:
  desc: null
  value: 41405489
n_inp:
  desc: null
  value: 1
